# Generated by Django 3.1.14 on 2022-05-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TL_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tle',
            name='importance',
            field=models.IntegerField(default=1),
        ),
    ]
