# Generated by Django 3.1.14 on 2022-05-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TL_app', '0003_tle_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tle',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='tle',
            name='end_at',
            field=models.DateTimeField(auto_now=True, verbose_name='終了日時'),
        ),
        migrations.AddField(
            model_name='tle',
            name='start_at',
            field=models.DateTimeField(auto_now=True, verbose_name='開始日時'),
        ),
    ]
