# Generated by Django 3.1.14 on 2022-05-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TL_app', '0004_auto_20220525_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tle',
            name='end_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='終了日時'),
        ),
    ]
