# Generated by Django 3.1.14 on 2022-05-26 08:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TL_app', '0007_auto_20220526_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='tl',
            name='abstract',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tl',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tl',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='tl',
            name='english',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
