# Generated by Django 3.1.14 on 2022-05-26 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TL_app', '0009_tle_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tle',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TL_app.tl', verbose_name=''),
        ),
    ]
