# Generated by Django 3.1.14 on 2022-05-30 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TL_app', '0010_auto_20220526_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='tl',
            name='genre',
            field=models.CharField(choices=[('people', '人物'), ('Corporate', '企業'), ('school', '学校'), ('sport', 'スポーツ'), ('science', '科学'), ('culture', '文化'), ('other', '両足')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tle',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TL_app.tl'),
        ),
    ]
