# Generated by Django 3.1.14 on 2022-05-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TL_app', '0011_auto_20220530_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tl',
            name='genre',
            field=models.CharField(choices=[('people', '人物'), ('Corporate', '企業'), ('school', '学校'), ('sport', 'スポーツ'), ('science', '科学'), ('culture', '文化'), ('nature', '自然'), ('politics・economy', '政治・経済'), ('nation・city', '国家・都市'), ('region', '地域'), ('religion', '宗教'), ('organization', '団体'), ('space', '宇宙'), ('other', 'その他')], default='', max_length=255),
        ),
    ]
