# Generated by Django 3.1.14 on 2022-06-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TL_app', '0012_auto_20220530_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='TL_year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=1800)),
            ],
        ),
    ]
