# Generated by Django 3.1.14 on 2022-06-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TL_app', '0013_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='year',
            name='TL',
        ),
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.IntegerField(),
        ),
    ]
