# Generated by Django 3.1.14 on 2022-06-02 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TL_app', '0013_tl_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tl_year',
            old_name='year',
            new_name='tl_year',
        ),
    ]
