# Generated by Django 3.1.14 on 2022-06-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TL_app', '0014_auto_20220602_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='TL',
            field=models.ManyToManyField(blank=True, to='TL_app.TL'),
        ),
    ]
