# Generated by Django 3.1.14 on 2022-06-02 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TL_app', '0015_year_tl'),
    ]

    operations = [
        migrations.AddField(
            model_name='tle',
            name='year',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='TL_app.year'),
            preserve_default=False,
        ),
    ]
