# Generated by Django 3.1.14 on 2022-06-02 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TL_app', '0016_tle_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tle',
            name='year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='TL_app.tl_year'),
        ),
    ]
