# Generated by Django 3.1.14 on 2022-06-02 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TL_app', '0017_auto_20220602_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='year',
            options={'ordering': ['year']},
        ),
        migrations.AlterField(
            model_name='tle',
            name='year',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='TL_app.year'),
        ),
        migrations.DeleteModel(
            name='TL_year',
        ),
    ]
