# Generated by Django 3.1.14 on 2022-06-02 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TL_app', '0018_auto_20220602_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tle',
            name='year',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tle', to='TL_app.year'),
        ),
        migrations.AlterField(
            model_name='year',
            name='TL',
            field=models.ManyToManyField(blank=True, related_name='year', to='TL_app.TL'),
        ),
    ]
