# Generated by Django 3.1.14 on 2022-06-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TL_app', '0019_auto_20220603_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tle',
            name='year',
            field=models.IntegerField(default=1800),
        ),
        migrations.AlterField(
            model_name='year',
            name='TL',
            field=models.ManyToManyField(blank=True, to='TL_app.TL'),
        ),
    ]
