# Generated by Django 3.1.14 on 2022-06-08 23:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TL_app', '0020_auto_20220607_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='tle',
            name='rank',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.DeleteModel(
            name='year',
        ),
    ]
