# Generated by Django 3.1.14 on 2022-06-09 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TL_app', '0021_auto_20220609_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tle',
            name='importance',
        ),
    ]
