# Generated by Django 3.1.14 on 2022-06-15 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TL_app', '0022_remove_tle_importance'),
    ]

    operations = [
        migrations.AddField(
            model_name='tle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
