# Generated by Django 3.1.14 on 2022-06-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TL_app', '0023_tle_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tl',
            name='date',
        ),
        migrations.AddField(
            model_name='tl',
            name='end_year',
            field=models.IntegerField(default=1800),
        ),
        migrations.AddField(
            model_name='tl',
            name='start_year',
            field=models.IntegerField(default=1800),
        ),
    ]
