# Generated by Django 3.1.14 on 2022-06-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TL_app', '0024_auto_20220615_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tle',
            name='end_at',
        ),
        migrations.RemoveField(
            model_name='tle',
            name='start_at',
        ),
        migrations.AddField(
            model_name='tl',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
