# Generated by Django 3.1.14 on 2022-06-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TL_app', '0025_auto_20220616_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tl',
            old_name='image',
            new_name='mainimage',
        ),
        migrations.AddField(
            model_name='tl',
            name='tagimage',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
