# Generated by Django 3.1.14 on 2022-06-17 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TL_app', '0026_auto_20220616_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='tle',
            name='body',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
