# Generated by Django 3.1.14 on 2022-06-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TL_app', '0028_auto_20220620_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tle',
            name='map',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tle',
            name='video',
            field=models.TextField(default=''),
        ),
    ]
